### ISSUE TITLE
npm install fail on windows 10

### ISSUE THREAD

**Issue by cool-firer** [substack/node-bigint#40]
output: 
```
$ npm install bigint

> bigint@0.4.2 install D:\work\WebStorm\sshclientest\node_modules\bigint
> node-gyp configure build


D:\work\WebStorm\sshclientest\node_modules\bigint>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build )  else (node "" configure build )
▒ڴ˽▒▒▒▒▒▒▒▒һ▒▒▒▒▒▒һ▒▒▒▒Ŀ▒▒▒▒Ҫ▒▒▒ò▒▒▒▒▒▒ɣ▒▒▒▒▒ӡ▒/m▒▒▒▒▒ء▒
MSBUILD : error MSB3428: δ▒ܼ▒▒▒ Visual C++ ▒▒▒▒▒VCBuild.exe▒▒▒▒Ҫ▒▒▒▒▒▒▒▒⣬1) ▒▒װ .NET Framework 2.0 SDK▒▒2) ▒▒װ Microsoft Visual Studio 2005▒▒▒▒ 3) ▒▒▒▒▒▒▒▒▒▒▒▒װ▒▒▒▒▒▒▒▒λ▒ã▒▒뽫▒▒λ▒▒▒▒ӵ▒ϵͳ·▒▒▒С▒ [D:\work\WebStorm\sshclientest\node_modules\bigint\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd D:\work\WebStorm\sshclientest\node_modules\bigint
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\work\WebStorm\sshclientest\package.json'
npm WARN sshclientest No description
npm WARN sshclientest No repository field.
npm WARN sshclientest No README data
npm WARN sshclientest No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bigint"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! bigint@0.4.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bigint@0.4.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bigint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bigint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bigint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\WebStorm\sshclientest\npm-debug.log


```

**Comment by unruledboy** [comment]
Same issue, if we open the detailed log, it would say something like this:

87 error \node_modules\bigint\bigint.cc(9): fatal error C1083: Cannot open include file: 'gmp.h': No such file or directory [\node_modules\bigint\build\bigint.vcxproj]

**Comment by Edduard** [comment]
> Same issue, if we open the detailed log, it would say something like this:
> 
> 87 error \node_modules\bigint\bigint.cc(9): fatal error C1083: Cannot open include file: 'gmp.h': No such file or directory [\node_modules\bigint\build\bigint.vcxproj]

Same issue here. Have you found any solution?
