### ISSUE TITLE
Fails to build on FreeBSD

### ISSUE THREAD

**Issue by khanzf** [substack/node-bigint#42]
I receive the following error when attempting to build this on FreeBSD.
I have gmp.h in /usr/local/include/
I cannot identify which build script allows me to include the file path.
```
[farhan@workbench ~/node-bigint]$ uname -or
FreeBSD 11.1-RELEASE-p9
[farhan@workbench ~/node-bigint]$ ls -l /usr/local/include/gmp.h
-rw-r--r--  1 root  wheel  83685 Apr  5 01:20 /usr/local/include/gmp.h
[farhan@workbench ~/node-bigint]$ npm install

> bigint@0.4.2 install /usr/home/farhan/node-bigint
> node-gyp configure build

gmake: Entering directory '/usr/home/farhan/node-bigint/build'
  CXX(target) Release/obj.target/bigint/bigint.o
../bigint.cc:9:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^~~~~~~
1 error generated.
gmake: *** [bigint.target.mk:93: Release/obj.target/bigint/bigint.o] Error 1
gmake: Leaving directory '/usr/home/farhan/node-bigint/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System FreeBSD 11.1-RELEASE-p9
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /usr/home/farhan/node-bigint
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bigint@0.4.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bigint@0.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/farhan/.npm/_logs/2018-05-24T19_18_28_472Z-debug.log
```

**Comment by khanzf** [comment]
I went ahead and added freebsd support to the bindings.gyp, but it still fails.
This also fails on Linux at the same point.
